spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jpashop
    username: root
    password: qwer1234

  jpa:
    hibernate:
      # 이 옵션은 애플리케이션 실행 시점에 테이브를 drop하고, 다시 생성한다.
      ddl_auto: create

    properties:
      hibernate:
        format_sql: true

logging.level:
  org.hibernate.SQL: debug